language: node_js
node_js:
  - node
notifications:
  slack:
    secure: Te6qCKM5v5A/lzPOaJUUBPSImhwl1GB0Jl4gWT7AjnxRia9bauY7leH6uR3PT1BCmx56LLhcWNH8jNckMJdM+zbRzOd3Yu934LaiycQUAhTITSQW0pc5/WrZskDKq74KFxCSf3/QuuZf7WrOspFhPbksnWsz8DWOix1IpEkDdm5doaAU7xjyMRy6Iqo0+Jh1gZYe62FXtpXAR8KscQQZ8psUME6VBbYwmG+uLmLnQ/d4GangQjHgYWGTbge0k8Dap5iJMkxdvbKrPjEJX1uPvvPZa8Uj0W9qNNBOPbo41Bxb7T9EPbeISvBqS4vofySkpYZwFbolj71i16XLl4CBDrMt+bKnIWn5yN0MCM6kOt4sBmHcERbT5WPS9acVuuCQbVDTGAAthnZ8Sq+LXmKObd+Dgny9VhCxHhIhGfc7UfXosdfasn3stUkVovq/jsRmp2uVKbj3KuV5+lFlL+/1C0CxAVWUE1wuN/TC5Smat+dfVavVbNd+45HiSpEZ6U1mRqhLxTQnEsoNmlwW3jwuDYgywPs20yR3XCd/TbuEt2TkVK8TDUZ00Py+bMAYe/eXuqZdH4nJM869BuYXIg/UAYCLZ+ROZcV/oTIKNSPNJh+dqshhHrc5QO5y09TkGwzxWysewl5B+3v4UsTSgZnKlY27XLmGRTJhrXkLiwNvUV0=
